dev:
  parameters:
    LogLevel: DEBUG
    RetentionInDays: "7"

tests:
  parameters:
    LogLevel: DEBUG
    RetentionInDays: "30"

staging:
  parameters:
    LogLevel: DEBUG
    RetentionInDays: "30"

prod:
  parameters:
    LogLevel: INFO
    RetentionInDays: "30"
  flags:
    can-test: false
    is-prod: true