dev:
  parameters:
    LogLevel: DEBUG
    RetentionInDays: 7

tests:
  parameters:
    LogLevel: DEBUG
    RetentionInDays: 30

staging:
  parameters:
    LogLevel: DEBUG
    RetentionInDays: 30

prod:
  parameters:
    LogLevel: INFO
    RetentionInDays: 30
  flags:
    can-integ: false
    is-prod: true