AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Environment:
    Type: String
    Default: dev


Resources:
  EnvironmentParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ecommerce/platform/environment
      Type: String
      Value: !Ref Environment

  #############
  # EVENT BUS #
  #############
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: ecommerce

  EventBusNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ecommerce/platform/event-bus/name
      Type: String
      Value: !Ref EventBus