openapi: "3.0.2"
info:
  title: Products API
  version: 1.0.0
  description: Products service API definition
  license:
    name: MIT-0

paths:
  /backend/validate:
    post:
      description: |
        Validates an array of products.

        This will return a 4XX error if there are discrepancies between products
        in the request and database.

        __Remark__: This is an internal API that requires valid IAM credentials
        and signature.
      operationId: backendValidateProducts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../shared/resources/schemas.yaml#/Products"
      responses:
        4XX:
          description: Invalid products
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../shared/resources/schemas.yaml#/Products"
                  - $ref: "../../shared/resources/schemas.yaml#/Message"
        default:
          description: OK or server error
          content:
            application/json:
              schema:
                $ref: "../../shared/resources/schemas.yaml#/Message"
      x-amazon-apigateway-auth:
        type: AWS_IAM
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        type: aws_proxy
        uri:
          Fn::Sub: "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ValidateFunction.Arn}/invocations"
