version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
  pre_build:
    commands:
      - apt-get update -y
      - apt-get install -y jq
      - /usr/bin/env python3.8 -m pip install --upgrade pip
      - make requirements
      - npm install -g speccy jq
  build:
    commands:
      - COMMIT_ID=$(aws ssm get-parameter --name $COMMIT_PARAMETER | jq -r '.Parameter.Value')
      - "echo SERVICES: $(tools/pipeline changed $COMMIT_ID)"
      # Tests for all services must work before moving to the next step
      - |
        for SERVICE in $(tools/pipeline changed $COMMIT_ID); do
          make ci-$SERVICE package-$SERVICE || exit 1
        done
      # Upload template artifacts to 'templates/$SERVICE.yaml'
      # This will trigger the pipelines per service
      - |
        for SERVICE in $(tools/pipeline changed $COMMIT_ID); do
          tools/pipeline upload $SERVICE || exit 1
        done
      # Update the parameter
      - aws ssm put-parameter --name $COMMIT_PARAMETER --type String --value $CODEBUILD_RESOLVED_SOURCE_VERSION --overwrite