name: tests

on:
  pull_request:
    branches:
      - master
    paths:
      - "*/**"
      - "!docs/**"
  push:
    branches:
      - master
    paths:
      - "*/**"
      - "!docs/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup python-3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: setup node-12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          make requirements
          npm install -g speccy
      - name: lint and unit tests
        run: |
          echo "SERVICES:" */metadata.yaml
          for metafile in */metadata.yaml; do
            echo "Running tests on $(dirname metafile)"
            tools/toolbox $(dirname metafile) ci
          done
